# Generated by Django 4.2.5 on 2023-10-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0002_rename_username_login_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('noofperson', models.CharField(max_length=50)),
                ('typeofevent', models.CharField(max_length=50)),
            ],
        ),
    ]
