# Generated by Django 4.2.5 on 2023-10-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0003_bookingslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofevent', models.CharField(max_length=50)),
            ],
        ),
    ]
