# Generated by Django 4.2.5 on 2023-10-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0004_addevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addevent',
            old_name='typeofevent',
            new_name='events',
        ),
    ]
